spring.application.name=biodata-api

#CONFIG image
spring.servlet.multipart.max-file-size=5
spring.servlet.multipart.enabled=true

#Config Tomcat
server.port=8081
#CONFIGURASI PGSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/biodata
spring.datasource.username=postgres
spring.datasource.password=Datavesta27

#Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Hikari Pool Configuration
spring.datasource.hikari.pool-name=HikariPool
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=60000



# This will create table automatically in your database
spring.jpa.hibernate.ddl-auto=update

# jpa hibernate
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.show_sql=true

# folder images
file.upload-dir=D:/uploads
file.url.upload-dir=http://localhost:${server.port}/images/

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
